package frc.team2471.frc2026

import com.ctre.phoenix6.CANBus
import com.ctre.phoenix6.configs.CANcoderConfiguration
import com.ctre.phoenix6.configs.Slot0Configs
import com.ctre.phoenix6.configs.TalonFXConfiguration
import com.ctre.phoenix6.hardware.CANcoder
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants
import com.ctre.phoenix6.swerve.SwerveModuleConstants
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory
import org.team2471.frc.lib.control.CurrentLimits
import org.team2471.frc.lib.ctre.getMagnetSensorOffset
import org.team2471.frc.lib.math.round
import org.team2471.frc.lib.units.asDegrees
import org.team2471.frc.lib.units.asFeet
import org.team2471.frc.lib.units.asMeters
import org.team2471.frc.lib.units.feetPerSecond
import org.team2471.frc.lib.units.inches
import org.team2471.frc.lib.units.meters
import org.team2471.frc.lib.units.asKilograms
import org.team2471.frc.lib.units.asMetersPerSecond
import org.team2471.frc.lib.units.asRotations
import org.team2471.frc.lib.units.asVolts
import org.team2471.frc.lib.units.degrees
import org.team2471.frc.lib.units.metersPerSecondPerSecond
import org.team2471.frc.lib.units.pounds
import org.team2471.frc.lib.units.volts
import org.team2471.frc.lib.util.isReal
import org.wpilib.driverstation.Alert
import org.wpilib.math.geometry.Translation2d
import org.wpilib.math.system.DCMotor
import org.wpilib.units.measure.Distance
import org.wpilib.units.measure.LinearAcceleration
import org.wpilib.units.measure.LinearVelocity
import org.wpilib.util.Preferences
import kotlin.math.roundToInt

// Generated by the Tuner X Swerve Project Generator. Originally named TunerConstants and reformatted/restructured to work better with kotlin
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
object DriveConstants {
    val driveMotor = DCMotor.getKrakenX60Foc(1)!!
    val steerMotor = DCMotor.getKrakenX44(1)!!

    private val driveGearRatio = if (Robot.isCompBot) 7.125 else 6.746031746031747
    private val steerGearRatio = if (Robot.isCompBot) 18.75 else 21.428571428571427
    private val wheelRadiusInches = 2.0 * if (Robot.isCompBot) ((89.5 / 96.0) * (97.0 / 96.0)) else (0.950495049505 * (9.33 / 8.0) * (0.9479) * (106.0 / 96.0) * (91.0 / 96.0) * (94.5/96.0))

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private val steerGains: Slot0Configs = Slot0Configs().apply {
        kP = 2.4817 * steerGearRatio
        kI = 0.0
        kD = 0.0
        kS = 0.073174
        kV = 2.6622
        kA = 0.05389
        StaticFeedforwardSign = StaticFeedforwardSignValue.UseClosedLoopSign
    }

    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private val driveGains: Slot0Configs = Slot0Configs().apply {
        if (Robot.isCompBot) {
            kP = 0.1875
            kI = 0.0
            kD = 0.0
            kS = 0.15
            kV = 0.1265
            kA = 0.00892
        } else {
            kP = 0.135
            kI = 0.0
            kD = 0.0
            kS = 0.15
            kV = 0.087
            kA = 0.00892
        }

    }

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    val driveCANBus: CANBus = CANBus("rio", "./logs/example.hoot")

    // Theoretical free speed at 12 V applied output;
    // This needs to be tuned to your individual robot
    val kSpeedAt12Volts: LinearVelocity = (driveMotor.freeSpeed / driveGearRatio * wheelRadiusInches.inches.asFeet).feetPerSecond * 0.9  //3.91.metersPerSecond (12.8 fps) -2025
    val robotWeight = 150.0.pounds
    // Max linear acceleration (m/s²) = force per amp * (60 amp stator current limit - free current) * gear ratio * 85% drivetrain efficiency / wheel radius / robot mass
    val kMaxAcceleration: LinearAcceleration = (driveMotor.Kt * (60.0 - driveMotor.freeCurrent) * driveGearRatio * 0.85 / wheelRadiusInches.inches.asMeters / robotWeight.asKilograms).metersPerSecondPerSecond

    val drivetrainConstants: SwerveDrivetrainConstants = SwerveDrivetrainConstants().apply {
        CANBusName = driveCANBus.name
        Pigeon2Id = CANSensors.PIGEON
        Pigeon2Configs = null //Leave this null to skip applying Pigeon 2 configs
    }

    val driveMaxCurrentLimits = CurrentLimits(40.0, 50.0, 0.5)
    val driveAutoCurrentLimits = driveMaxCurrentLimits
    val driveTeleCurrentLimits = CurrentLimits(33.0, 33.0, 0.5)

    private val constantCreator: SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> =
        SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>().apply {
            /**
             * Initial configs for the drive/steer motors and encoder, these cannot be null.
             * Some configs will be overwritten; see the withInitialConfigs() API documentation.
             *
             * @see SwerveModuleConstants.withDriveMotorInitialConfigs
             * @see SwerveModuleConstants.withSteerMotorInitialConfigs
             * @see SwerveModuleConstants.withEncoderInitialConfigs
              */
            DriveMotorInitialConfigs = TalonFXConfiguration().apply {
                CurrentLimits.apply {
                    SupplyCurrentLimit = driveAutoCurrentLimits.peakLimit
                    SupplyCurrentLowerLimit = driveAutoCurrentLimits.continuousLimit
                    SupplyCurrentLowerTime = driveAutoCurrentLimits.peakDuration
                    SupplyCurrentLimitEnable = true
                }
            }
            SteerMotorInitialConfigs = TalonFXConfiguration().apply {
                CurrentLimits.apply{
                    SupplyCurrentLimit = 10.0
                    SupplyCurrentLimitEnable = true
                }
            }
            EncoderInitialConfigs = CANcoderConfiguration()

            /** Gear ratios for steer and drive motors. The number of motor rotations for 1 wheel rotation */
            DriveMotorGearRatio = driveGearRatio
            SteerMotorGearRatio = steerGearRatio

            /**
             * The ratio at which the drive motor spins when the steer turret spins (driveMotorRotations/SteerRotations)
             * Every 1 rotation of the steer results in [SwerveModuleConstantsFactory.CouplingGearRatio] drive motor turns.
             * Found by wedging an object inside the drive wheel (preventing the wheel from spinning) then
             * measuring the change of the drive motor position when the steer turret is rotated 1 rotation.
             **/
            CouplingGearRatio = if (Robot.isCompBot) 3.125 else 3.5714285714285716

            /**
             * Type of closed loop output: Torque or Voltage
             * This affects the units of [SwerveModuleConstantsFactory.DriveMotorGains] PID gains for the motors.
             */
            DriveMotorClosedLoopOutput = SwerveModuleConstants.ClosedLoopOutputType.Voltage
            SteerMotorClosedLoopOutput = SwerveModuleConstants.ClosedLoopOutputType.Voltage

            /** PID and [Slot0Configs] of motors */
            DriveMotorGains = driveGains
            SteerMotorGains = steerGains

            /**
             * The stator current at which the wheels start to slip, in amps.
             * Maximum amount of stator current the drive motors can apply without slippage.
            */
            SlipCurrent = 60.0

            /** The max speed of the robot when driven with 12 volts. m/s */
            SpeedAt12Volts = kSpeedAt12Volts.asMetersPerSecond

            /**
             * Type of motor controller
             * The type of motor used for the drive/steer motor
            */
            DriveMotorType = SwerveModuleConstants.DriveMotorArrangement.TalonFX_Integrated
            SteerMotorType = SwerveModuleConstants.SteerMotorArrangement.TalonFX_Integrated

            /**
             * How to use the CANCoder. (Remote, Fused, or Synced)
             * The remote sensor feedback type to use for the steer motors;
             * When not Pro-licensed, FusedCANcoder/SyncCANcoder automatically falls back to RemoteCANcoder
            */
            // Sync doesn't work in sim
            FeedbackSource = if (isReal) SwerveModuleConstants.SteerFeedbackType.SyncCANcoder else SwerveModuleConstants.SteerFeedbackType.FusedCANcoder

            /** Moment of Inertia. Only used in simulation */
            DriveInertia = 0.025
            SteerInertia = 0.0000000004

            /** Simulated voltage required to overcome friction. Only used in simulation */
            DriveFrictionVoltage = 0.2.volts.asVolts
            SteerFrictionVoltage = 0.2.volts.asVolts

            WheelRadius = wheelRadiusInches.inches.asMeters //<- wheel radius can be overridden during module config
        }

    //Usually swerve drives are square
    val moduleTrackWidth = 11.0.inches

    val frontLeft = ModuleConfig(
        Falcons.FRONT_LEFT_DRIVE,
        Falcons.FRONT_LEFT_STEER,
        CANCoders.FRONT_LEFT,
        driveMotorInverted = false,
        steerMotorInverted = true,
        encoderInverted = false,
        moduleTranslationMeters = Translation2d(moduleTrackWidth.asMeters, moduleTrackWidth.asMeters),
        id = 0,
        wheelRadiusOverride = null,
        driveMotorGainsOverride = null
    ).createModuleConstants()

    val frontRight = ModuleConfig(
        Falcons.FRONT_RIGHT_DRIVE,
        Falcons.FRONT_RIGHT_STEER,
        CANCoders.FRONT_RIGHT,
        driveMotorInverted = false,
        steerMotorInverted = true,
        encoderInverted = false,
        moduleTranslationMeters = Translation2d(moduleTrackWidth.asMeters, -moduleTrackWidth.asMeters),
        id = 1,
        wheelRadiusOverride = null,
        driveMotorGainsOverride = null
    ).createModuleConstants()

    val backLeft = ModuleConfig(
        Falcons.BACK_LEFT_DRIVE,
        Falcons.BACK_LEFT_STEER,
        CANCoders.BACK_LEFT,
        driveMotorInverted = false,
        steerMotorInverted = true,
        encoderInverted = false,
        moduleTranslationMeters = Translation2d(-moduleTrackWidth.asMeters, moduleTrackWidth.asMeters),
        id = 2,
        wheelRadiusOverride = null,
        driveMotorGainsOverride = null
    ).createModuleConstants()

    val backRight = ModuleConfig(
        Falcons.BACK_RIGHT_DRIVE,
        Falcons.BACK_RIGHT_STEER,
        CANCoders.BACK_RIGHT,
        driveMotorInverted = false,
        steerMotorInverted = true,
        encoderInverted = false,
        moduleTranslationMeters = Translation2d(-moduleTrackWidth.asMeters, -moduleTrackWidth.asMeters),
        id = 3,
        wheelRadiusOverride = null,
        driveMotorGainsOverride = null
    ).createModuleConstants()


    val moduleConfigs = arrayOf(frontLeft, frontRight, backLeft, backRight)

    init {
        println("TunerConstants created ${moduleConfigs.size} modules.")
    }


    class ModuleConfig(
        val driveMotorID: Int,
        val steerMotorID: Int,
        val canCoderID: Int,
        val driveMotorInverted: Boolean,
        val steerMotorInverted: Boolean,
        val encoderInverted: Boolean,
        val moduleTranslationMeters: Translation2d,
        val id: Int,
        val wheelRadiusOverride: Distance? = null,
        val driveMotorGainsOverride: Slot0Configs? = null,
    ) {
        fun createModuleConstants(): SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> {

            val canCoder = CANcoder(canCoderID, driveCANBus)
            var magnetSensorOffset = canCoder.getMagnetSensorOffset()

            //Use NT preferences as a backup to check if the encoder offset is valid
            if (canCoder.isConnected) {
                val prefsOffset = Preferences.getDouble("Module $id Offset", Double.NaN).degrees
                if (prefsOffset.asDegrees.isNaN()) {
                    //couldn't find prefs
                    println("Module $id has missing Preferences, setting to encoders Offset: ${magnetSensorOffset.asDegrees.roundToInt()}")
                    Preferences.setDouble("Module $id Offset", magnetSensorOffset.asDegrees)
                    Alert("Module $id had missing offset prefs", Alert.Level.MEDIUM).set(true)
                } else if (prefsOffset.asDegrees.roundToInt() != magnetSensorOffset.asDegrees.roundToInt()) {
                    //offsets are different, default to prefs
                    println("Module $id has conflicting offsets. prefsOffset: ${prefsOffset.asDegrees.round(2)} encoders Offset: ${magnetSensorOffset.asDegrees.round(2)}")
                    magnetSensorOffset = prefsOffset
                    Alert("Module $id had conflicting encoder offsets", Alert.Level.MEDIUM).set(true)
                }
            } else {
                Alert("Module $id CANCoder Disconnected On INIT", Alert.Level.HIGH).set(true)
            }


            return constantCreator.createModuleConstants(
                steerMotorID,
                driveMotorID,
                canCoderID,
                magnetSensorOffset.asRotations,
                moduleTranslationMeters.x.meters.asMeters,
                moduleTranslationMeters.y.meters.asMeters,
                driveMotorInverted,
                steerMotorInverted,
                encoderInverted
            ).apply {
                if (driveMotorGainsOverride != null) DriveMotorGains = driveMotorGainsOverride
                if (wheelRadiusOverride != null) WheelRadius = wheelRadiusOverride.asMeters
            }
        }
    }
}